### ISSUE TITLE
OU's under domain controllers are not enumerated

### ISSUE THREAD

**Issue by nicknomo** [aikoncwd/vbs-ad-health-report#1]
Just FYI, if the DC is in an OU inside of Domain Controllers (or the OU you specify, its not added to the array of computer to check).

**Comment by aikoncwd** [comment]
Then set `usingOU = False` and specify DC-server-names inside the array. While usingOU is set to False, the OU parameter is ignored.

**Comment by nicknomo** [comment]
Thanks for the reply.  While that would work, it does require manual entry every time a DC is added or removed.

I'm thinking you could just call a function and run it recursively on the sub OU's,  I could write this with a little bit of time, if you'd like...

**Comment by nicknomo** [comment]
I made a pull request regarding the changes.  I had some problems with the hardware checks. If the hardware wasn't available, the script failed. It also failed on my end due to the GB conversion... Hopefully this helps..
